spring:
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 40MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mariadb://localhost:3306/petshop
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  token:
    expiration-time: 31536000 # 1 year xD

app:
  static-resources:
    basePath: ${HOME}/app-images
    path: ${app.static-resources.basePath}/petshop/pets
